<?php
/**
 * Plugin Name: Thumbnail Downloader Log Viewer (Dark Mode)
 * Description: Standalone dark-mode log monitor for JSON Thumbnail Downloader Pro activity logs.
 * Version: 1.0.0
 * Author: Development Team
 * Requires at least: 6.0
 * Requires PHP: 7.4
 * Text Domain: tdlv
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Thumbnail_Downloader_Log_Viewer {
	const VERSION = '1.0.0';

	const SOURCE_OPTION_LOGS   = 'tdp_logs';
	const SOURCE_OPTION_ERRORS = 'tdp_errors';

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'admin_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );

		add_action( 'wp_ajax_tdlv_get_logs', array( $this, 'ajax_get_logs' ) );
		add_action( 'wp_ajax_tdlv_get_stats', array( $this, 'ajax_get_stats' ) );
	}

	public function admin_menu() {
		add_menu_page(
			esc_html__( 'TDP Log Viewer', 'tdlv' ),
			esc_html__( 'TDP Log Viewer', 'tdlv' ),
			'manage_options',
			'tdp-log-viewer',
			array( $this, 'render_page' ),
			'dashicons-list-view',
			59
		);
	}

	public function enqueue_assets( $hook ) {
		if ( 'toplevel_page_tdp-log-viewer' !== $hook ) {
			return;
		}

		wp_enqueue_style(
			'tdlv-admin-style',
			plugin_dir_url( __FILE__ ) . 'assets/admin-style.css',
			array(),
			self::VERSION
		);

		wp_enqueue_script(
			'tdlv-admin-script',
			plugin_dir_url( __FILE__ ) . 'assets/admin-script.js',
			array(),
			self::VERSION,
			true
		);

		wp_localize_script(
			'tdlv-admin-script',
			'tdlvData',
			array(
				'ajaxUrl' => admin_url( 'admin-ajax.php' ),
				'nonce'   => wp_create_nonce( 'tdlv_nonce' ),
			)
		);
	}

	public function render_page() {
		?>
		<div class="wrap tdlv-wrap">
			<div class="tdlv-header">
				<h1><?php esc_html_e( 'Thumbnail Downloader Log Viewer', 'tdlv' ); ?></h1>
				<p><?php esc_html_e( 'Dark-mode, real-time visibility into logs generated by JSON Thumbnail Downloader Pro.', 'tdlv' ); ?></p>
			</div>

			<div class="tdlv-grid">
				<div class="tdlv-stat"><span id="tdlv-total">0</span><small><?php esc_html_e( 'Total Logs', 'tdlv' ); ?></small></div>
				<div class="tdlv-stat"><span id="tdlv-success">0</span><small><?php esc_html_e( 'Success', 'tdlv' ); ?></small></div>
				<div class="tdlv-stat"><span id="tdlv-error">0</span><small><?php esc_html_e( 'Errors', 'tdlv' ); ?></small></div>
				<div class="tdlv-stat"><span id="tdlv-info">0</span><small><?php esc_html_e( 'Info', 'tdlv' ); ?></small></div>
				<div class="tdlv-stat"><span id="tdlv-last">—</span><small><?php esc_html_e( 'Last Event', 'tdlv' ); ?></small></div>
			</div>

			<div class="tdlv-toolbar">
				<input id="tdlv-search" type="text" placeholder="Search messages / JSON data" />
				<select id="tdlv-level">
					<option value="all"><?php esc_html_e( 'All levels', 'tdlv' ); ?></option>
					<option value="SUCCESS"><?php esc_html_e( 'SUCCESS', 'tdlv' ); ?></option>
					<option value="ERROR"><?php esc_html_e( 'ERROR', 'tdlv' ); ?></option>
					<option value="INFO"><?php esc_html_e( 'INFO', 'tdlv' ); ?></option>
				</select>
				<button class="button button-primary" id="tdlv-refresh"><?php esc_html_e( 'Refresh', 'tdlv' ); ?></button>
				<label class="tdlv-toggle"><input type="checkbox" id="tdlv-auto" checked /> Auto-refresh</label>
			</div>

			<div class="tdlv-log-panel" id="tdlv-log-panel" role="log" aria-live="polite"></div>
			<p class="description">Source options: <code>tdp_logs</code> and <code>tdp_errors</code> from JSON Thumbnail Downloader Pro.</p>
		</div>
		<?php
	}

	public function ajax_get_logs() {
		check_ajax_referer( 'tdlv_nonce', 'nonce' );
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'Unauthorized' );
		}

		$search = isset( $_POST['search'] ) ? sanitize_text_field( wp_unslash( $_POST['search'] ) ) : '';
		$level  = isset( $_POST['level'] ) ? sanitize_text_field( wp_unslash( $_POST['level'] ) ) : 'all';
		$limit  = isset( $_POST['limit'] ) ? max( 10, min( 500, (int) $_POST['limit'] ) ) : 200;

		$logs   = get_option( self::SOURCE_OPTION_LOGS, array() );
		$errors = get_option( self::SOURCE_OPTION_ERRORS, array() );

		$error_logs = array_map(
			function( $entry ) {
				return array(
					'time'      => isset( $entry['time'] ) ? $entry['time'] : current_time( 'mysql' ),
					'timestamp' => time(),
					'level'     => 'ERROR',
					'message'   => isset( $entry['message'] ) ? $entry['message'] : 'Unknown error',
					'data'      => isset( $entry['data'] ) ? $entry['data'] : array(),
				);
			},
			is_array( $errors ) ? $errors : array()
		);

		$merged = array_merge( is_array( $logs ) ? $logs : array(), $error_logs );

		usort(
			$merged,
			function( $a, $b ) {
				$at = isset( $a['timestamp'] ) ? (int) $a['timestamp'] : strtotime( (string) ( $a['time'] ?? '' ) );
				$bt = isset( $b['timestamp'] ) ? (int) $b['timestamp'] : strtotime( (string) ( $b['time'] ?? '' ) );
				return $bt <=> $at;
			}
		);

		$filtered = array_values(
			array_filter(
				$merged,
				function( $entry ) use ( $search, $level ) {
					$entry_level = isset( $entry['level'] ) ? strtoupper( (string) $entry['level'] ) : 'INFO';
					if ( 'all' !== $level && strtoupper( $level ) !== $entry_level ) {
						return false;
					}

					if ( '' === $search ) {
						return true;
					}

					$haystack = wp_json_encode( $entry );
					return false !== stripos( $haystack, $search );
				}
			)
		);

		$filtered = array_slice( $filtered, 0, $limit );

		wp_send_json_success(
			array(
				'logs' => $filtered,
			)
		);
	}

	public function ajax_get_stats() {
		check_ajax_referer( 'tdlv_nonce', 'nonce' );
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'Unauthorized' );
		}

		$logs = get_option( self::SOURCE_OPTION_LOGS, array() );
		if ( ! is_array( $logs ) ) {
			$logs = array();
		}

		$stats = array(
			'total'   => count( $logs ),
			'success' => 0,
			'error'   => 0,
			'info'    => 0,
			'last'    => '—',
		);

		foreach ( $logs as $entry ) {
			$level = isset( $entry['level'] ) ? strtoupper( (string) $entry['level'] ) : 'INFO';
			if ( 'SUCCESS' === $level ) {
				++$stats['success'];
			} elseif ( 'ERROR' === $level ) {
				++$stats['error'];
			} else {
				++$stats['info'];
			}
		}

		if ( ! empty( $logs[0]['time'] ) ) {
			$stats['last'] = sanitize_text_field( (string) $logs[0]['time'] );
		}

		wp_send_json_success( $stats );
	}
}

new Thumbnail_Downloader_Log_Viewer();
